# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "hapfill_setup"
description: HaploFill step 1: sequence splitting, pairing setup, repeat parsing, gap detection
keywords:
  - haplosync
  - genome assembly
tools:
  - "hapfill_setup.py":
      description: "Part of the HaploSync pipeline (hapfill_setup.py)"
      documentation: "https://github.com/noecochetel/HaploSync"
input:
  - hap1_fasta:
      type: file
      description: Hap1 pseudomolecule FASTA
  - hap2_fasta:
      type: file
      description: Hap2 pseudomolecule FASTA
  - un_fasta:
      type: file
      description: Unplaced sequences FASTA
  - correspondence:
      type: file
      description: Chromosome Hap1/Hap2 correspondence TSV
  - repeats:
      type: file
      description: repeats
output:
  - versions:
      type: file
      description: Tool version YAML
  - temp_dir:
      type: file
      description: HaploFill temp working directory (carried between steps)
authors:
  - "@noecochetel"
maintainers:
  - "@noecochetel"
