---
title: "Chromosome pair report"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    self_contained: true
params:
  filename : ""
  Hap1: ""
  Hap2: ""
  structure : ""
  legacy : ""
  markers : ""
  seq_relationships: ""
  marker_relationship: ""
  has_legacy: true
  has_markers: true
---

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(htmlwidgets))
suppressPackageStartupMessages(library(plyr))

# parse parameters ---------------------------------------------------------------
filename <- params$filename

Hap1 <- params$Hap1
Hap2 <- params$Hap2

agp_file <- params$structure
agp_legacy_file  <- params$legacy
markers_file <- params$markers
seq_rel_file <- params$seq_relationships
marker_rel_file <- params$marker_relationship

has_legacy  <- as.logical(params$has_legacy)
has_markers <- as.logical(params$has_markers)

# load data ---------------------------------------------------------------

agp <- read_tsv(agp_file, col_names = c("ID" , "start" , "stop" , "component" , "orientation", "group_id"))

if (has_legacy) {
  agp_legacy <- read_tsv(agp_legacy_file, col_names = c("ID" , "start" , "stop" , "component" , "orientation" , "group_id"))
}

seq_rel <- read_tsv(seq_rel_file, col_names = c("x" , "y" , "group_id" , "category") )
if (empty(seq_rel)) {
  seq_rel_p0 <- tibble()
} else {
  seq_rel_p0 <- seq_rel %>% filter(category == "hap1_to_hap2")
}

if (has_markers) {
  markers     <- read_tsv(markers_file,     col_names = c("ID" , "coords" , "marker_id" , "marker_order" , "Used") )
  marker_rel  <- read_tsv(marker_rel_file,  col_names = c("x1" , "y1" , "x2" , "y2" , "marker_order" , "marker_id" , "category" ))
}
```

```{r}
# Split input files
agp_hap1 <- agp %>% filter(ID == Hap1) %>% mutate(category = "hap1")
agp_hap2 <- agp %>% filter(ID == Hap2) %>% mutate(category = "hap2")

if (has_legacy) {
  agp_legacy_hap1 <- agp_legacy %>% filter(ID == Hap1) %>% mutate(category = "hap1")
  agp_legacy_hap2 <- agp_legacy %>% filter(ID == Hap2) %>% mutate(category = "hap2")
  hap1_len <- max(agp_legacy_hap1$stop)
  hap2_len <- max(agp_legacy_hap2$stop)
} else {
  hap1_len <- max(agp_hap1$stop)
  hap2_len <- max(agp_hap2$stop)
}

if (has_markers) {
  markers_hap1      <- markers %>% filter(ID == Hap1) %>% mutate(category = "hap1")
  markers_hap1_used <- markers_hap1 %>% filter(Used)
  markers_hap2      <- markers %>% filter(ID == Hap2) %>% mutate(category = "hap2")
  markers_hap2_used <- markers_hap2 %>% filter(Used)
  marker_rel_p0     <- marker_rel %>% filter(category == "hap1_to_hap2")
}

p0_facet_levels = c("hap1","hap1_to_hap2","hap2")
p0_facet_labels = c("Hap1" , "" , "Hap2")
names(p0_facet_labels) = p0_facet_levels

agp_hap1$category <- factor(agp_hap1$category, levels = p0_facet_levels)
agp_hap2$category <- factor(agp_hap2$category, levels = p0_facet_levels)

if (has_legacy) {
  agp_legacy_hap1$category <- factor(agp_legacy_hap1$category, levels = p0_facet_levels)
  agp_legacy_hap2$category <- factor(agp_legacy_hap2$category, levels = p0_facet_levels)
}

if (has_markers) {
  marker_rel_p0$category     <- factor(marker_rel_p0$category,     levels = p0_facet_levels)
  markers_hap1$category      <- factor(markers_hap1$category,      levels = p0_facet_levels)
  markers_hap1_used$category <- factor(markers_hap1_used$category, levels = p0_facet_levels)
  markers_hap2$category      <- factor(markers_hap2$category,      levels = p0_facet_levels)
  markers_hap2_used$category <- factor(markers_hap2_used$category, levels = p0_facet_levels)
}

seq_rel_p0$category <- factor(seq_rel_p0$category, levels = p0_facet_levels)

# Build interactive plot (no text labels for performance)
if (has_legacy) {
  p0_noLabels <- ggplot() +
    geom_rect(data = agp_hap1,        mapping = aes(xmin = start, xmax = stop, ymin = 0.5,  ymax = 0.75 , text = component ), size = 0.2, fill = "grey75", color = "black") +
    geom_rect(data = agp_legacy_hap1, mapping = aes(xmin = start, xmax = stop, ymin = 0,    ymax = 0.5  , text = sprintf( "Sequence ID: %s<br>Sequence group: %s" , component , group_id ) , fill = group_id ), size = 0.2, color = "black") +
    geom_rect(data = agp_legacy_hap2, mapping = aes(xmin = start, xmax = stop, ymin = 0.25, ymax = 0.75 , text = sprintf( "Sequence ID: %s<br>Sequence group: %s" , component , group_id ) , fill = group_id ), size = 0.2, color = "black") +
    geom_rect(data = agp_hap2,        mapping = aes(xmin = start, xmax = stop, ymin = 0,    ymax = 0.25 , text = component ), size = 0.2, fill = "grey75", color = "black")
} else {
  p0_noLabels <- ggplot() +
    geom_rect(data = agp_hap1, mapping = aes(xmin = start, xmax = stop, ymin = 0, ymax = 1 , text = component ), size = 0.2, fill = "grey75", color = "black") +
    geom_rect(data = agp_hap2, mapping = aes(xmin = start, xmax = stop, ymin = 0, ymax = 1 , text = component ), size = 0.2, fill = "grey75", color = "black")
}

if (has_markers) {
  # Marker y positions depend on whether legacy bands are present
  if (has_legacy) {
    mk_hap2_lo      <- 0.6  ;  mk_hap2_hi      <- 0.73
    mk_hap2_used_lo <- 0.53 ;  mk_hap2_used_hi <- 0.58
  } else {
    mk_hap2_lo      <- 0.85 ;  mk_hap2_hi      <- 0.98
    mk_hap2_used_lo <- 0.78 ;  mk_hap2_used_hi <- 0.83
  }
  if (!(empty(marker_rel_p0)))     { p0_noLabels <- p0_noLabels + geom_segment(data = marker_rel_p0,     mapping = aes(x = x1, y = y1, xend = x2, yend = y2, color = marker_order)) }
  if (!(empty(markers_hap1)))      { p0_noLabels <- p0_noLabels + geom_segment(data = markers_hap1,      mapping = aes(x = coords, y = 0.02, xend = coords, yend = 0.15, color = marker_order)) }
  if (!(empty(markers_hap1_used))) { p0_noLabels <- p0_noLabels + geom_segment(data = markers_hap1_used, mapping = aes(x = coords, y = 0.17, xend = coords, yend = 0.22), color = "white") }
  if (!(empty(markers_hap2)))      { p0_noLabels <- p0_noLabels + geom_segment(data = markers_hap2,      mapping = aes(x = coords, y = mk_hap2_lo, xend = coords, yend = mk_hap2_hi, color = marker_order)) }
  if (!(empty(markers_hap2_used))) { p0_noLabels <- p0_noLabels + geom_segment(data = markers_hap2_used, mapping = aes(x = coords, y = mk_hap2_used_lo, xend = coords, yend = mk_hap2_used_hi), color = "white") }
}

p0_noLabels <- p0_noLabels +
        scale_color_viridis_c(direction = -1, option = "D" , name = "Marker order" ) +
        facet_grid(rows = vars(category), scales = "free_y", space = "free_y", drop = FALSE, labeller = labeller(category = p0_facet_labels)) +
        scale_y_continuous(expand = c(0.01, 0.01)) +
        scale_alpha_manual(values = c(0.2, 1)) +
        labs(x = "Sequence position (bp)") +
        { if (has_legacy) scale_fill_discrete(drop = FALSE, name = "Sequence group") else scale_fill_discrete(name = "") } +

        theme(plot.title = element_text(color="black", size=20, face="plain", margin=margin(t=1,r=0,b=1,l=0,"mm")),
                   axis.title.x = element_text(color="black", size=8, face="plain", margin=margin(t=1,r=0,b=0,l=0,"mm")),
                   axis.title.y = element_blank(),
                   axis.text.x = element_text(color="black", size=8, face="plain", margin=margin(t=1,r=0,b=0,l=0,"mm"), hjust = 0.5),
                   axis.text.y = element_blank(),
                   axis.line.x = element_line(color="black", size=0.5, linetype="solid"),
                   axis.line.y = element_blank(),
                   axis.ticks.x = element_line(color="black", size=0.5, linetype="solid"),
                   axis.ticks.y = element_blank(),
                   plot.background = element_blank(),
                   panel.background = element_blank(),
                   panel.grid.major.y = element_blank(),
                   panel.grid.major.x = element_blank(),
                   panel.grid.minor.y = element_blank(),
                   panel.grid.minor.x = element_blank(),
                   panel.spacing = unit(0, "line"),
                   plot.margin=unit(c(1,1,1,1),"mm"),
                   legend.position="right")

a <- list(
  text = "Hap1 Vs. Hap2",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "left",
  align = "left",
  x = 0,
  y = 1,
  showarrow = FALSE
)

pl0 <- ggplotly( p0_noLabels, tooltip = "text" ) %>% layout(yaxis = list(fixedrange = TRUE) , annotations = a )

for (i in seq_along(pl0$x$data)) {
  pl0$x$data[[i]]$showlegend <- FALSE
}
```

```{r}
# pdf(NULL)
# ggsave(p0_noLabels, filename = paste0(filename,".pdf"), height = 10, width = 22)
# ggsave(p0_noLabels, filename = paste0(filename,".png"), height = 10, width = 22)
```

Hap1 Vs. Hap2
==============================================================
```{r}
pl0
```
