# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "hapfill_coverage"
description: "HaploFill step 2: per-chromosome coverage extraction (bedtools genomecov or mosdepth)"
keywords:
  - haplosync
  - genome assembly
tools:
  - "hapfill_coverage.py":
      description: "Part of the HaploSync pipeline (hapfill_coverage.py)"
      documentation: "https://github.com/noecochetel/HaploSync"
input:
  - chr_tuple:
      type: file
      description: "chr tuple: (chr name, chr length, chr fasta, bam, bai)"
output:
  - versions:
      type: file
      description: Tool version YAML
  - signal:
      type: file
      description: signal
  - range_bed:
      type: file
      description: range bed
authors:
  - "@noecochetel"
maintainers:
  - "@noecochetel"
